spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.19.151.233/5619pet
    username: myuser
    password: 123456 #???????
mybatis:
  type-aliases-package: com.wjr.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 9090
